-- Reorder the complete native watch list without replacing tracker Lua methods.
local events = CreateFrame("Frame")
local queued = false
local sorting = false
local lastRejectedOrder

local function ReadWatches()
    local entries = {}
    for index = 1, C_QuestLog.GetNumQuestWatches() do
        local questID = C_QuestLog.GetQuestIDForQuestWatchIndex(index)
        if not questID then
            return
        end
        local level = C_QuestLog.GetQuestDifficultyLevel(questID)
        if (issecretvalue and issecretvalue(level)) or type(level) ~= "number" or level <= 0 then
            level = math.huge
        end
        entries[index] = { id = questID, level = level, index = index }
    end
    return entries
end

local function SortQuestWatches()
    queued = false
    if InCombatLockdown() or sorting then
        return
    end
    local entries = ReadWatches()
    if not entries or #entries < 2 then
        return
    end
    table.sort(entries, function(a, b)
        if a.level ~= b.level then
            return a.level < b.level
        end
        return a.index < b.index
    end)
    local desiredIDs = {}
    local changed = false
    for index, entry in ipairs(entries) do
        desiredIDs[index] = tostring(entry.id)
        changed = changed or entry.index ~= index
    end
    if not changed then
        lastRejectedOrder = nil
        return
    end
    local desiredOrder = table.concat(desiredIDs, ",")
    if desiredOrder == lastRejectedOrder then
        return
    end

    -- Native add/remove APIs keep the next tracker rebuild in Blizzard's context.
    -- AddQuestWatch inserts at the front, so insert highest-to-lowest to leave
    -- the native list lowest-first. Reverse ties too to preserve their order.
    local selectedQuest = C_SuperTrack.GetSuperTrackedQuestID()
    sorting = true
    for index = #entries, 1, -1 do
        local entry = entries[index]
        C_QuestLog.RemoveQuestWatch(entry.id)
        C_QuestLog.AddQuestWatch(entry.id)
    end
    if selectedQuest and C_SuperTrack.GetSuperTrackedQuestID() ~= selectedQuest then
        C_SuperTrack.SetSuperTrackedQuestID(selectedQuest)
    end
    sorting = false

    -- Some client builds may impose their own insertion order. Do not keep cycling
    -- watches in response to the events generated by an unsuccessful reorder.
    local accepted = C_QuestLog.GetNumQuestWatches() == #entries
    for index, entry in ipairs(entries) do
        if C_QuestLog.GetQuestIDForQuestWatchIndex(index) ~= entry.id then
            accepted = false
            break
        end
    end
    if not accepted then
        lastRejectedOrder = desiredOrder
        print("Forever Tweaks: the client did not retain quest-level watch order.")
    else
        lastRejectedOrder = nil
    end
end

local function QueueSort()
    if sorting or queued then
        return
    end
    queued = true
    C_Timer.After(0, SortQuestWatches)
end

-- Zone changes also cause Blizzard to sort watches by its native criteria.
hooksecurefunc(C_QuestLog, "SortQuestWatches", QueueSort)
for _, event in ipairs({ "PLAYER_LOGIN", "PLAYER_ENTERING_WORLD", "PLAYER_REGEN_ENABLED",
    "QUEST_LOG_UPDATE", "QUEST_WATCH_LIST_CHANGED" }) do
    events:RegisterEvent(event)
end
events:SetScript("OnEvent", QueueSort)
